[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_interface_2024 = "CgfCat6x2Rqhh3o5oKHQZXSK8N2c15EbAYrg9HjzGh5o"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ivmidable/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
